version: '3.8'

services:
  backend:
    container_name: brokerai-backend
    image: python:3.11-slim
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: bash -c "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    
    # Limiti per backend
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.3'

  frontend:
    container_name: brokerai-frontend
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
    
    # Comando corretto per installare dipendenze e avviare
    command: >
      sh -c "
      npm install --legacy-peer-deps &&
      npm install --save-dev typescript @types/react @types/node --legacy-peer-deps &&
      npm run dev
      "
    
    # Limiti di memoria
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.5'
        reservations:
          memory: 200M
    
    # Variabili d'ambiente (senza NODE_ENV=production per evitare warning)
    environment:
      - NODE_OPTIONS=--max-old-space-size=256
      - NEXT_TELEMETRY_DISABLED=1
    
    stdin_open: true
    tty: true

networks:
  default:
    name: brokerai-network