# docker-compose.debug.yml
version: '3.8'

services:
  backend:
    container_name: brokerai-backend
    image: python:3.11-slim
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: bash -c "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    container_name: brokerai-frontend
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    stdin_open: true
    tty: true

networks:
  default:
    name: brokerai-network